"""initial schema

Revision ID: 001
Revises: 
Create Date: 2024-02-07 13:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_usage',
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('keyword')
    )
    op.create_table('telegram_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('IELTS', 'UZBEKISTAN', 'OTHER', name='groupcategory'), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'JOINED', 'LEFT', 'BANNED', 'ERROR', name='groupstatus'), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_groups_category'), 'telegram_groups', ['category'], unique=False)
    op.create_index(op.f('ix_telegram_groups_entity_id'), 'telegram_groups', ['entity_id'], unique=True)
    op.create_index(op.f('ix_telegram_groups_status'), 'telegram_groups', ['status'], unique=False)
    op.create_index(op.f('ix_telegram_groups_title'), 'telegram_groups', ['title'], unique=False)
    op.create_index(op.f('ix_telegram_groups_username'), 'telegram_groups', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_groups_username'), table_name='telegram_groups')
    op.drop_index(op.f('ix_telegram_groups_title'), table_name='telegram_groups')
    op.drop_index(op.f('ix_telegram_groups_status'), table_name='telegram_groups')
    op.drop_index(op.f('ix_telegram_groups_entity_id'), table_name='telegram_groups')
    op.drop_index(op.f('ix_telegram_groups_category'), table_name='telegram_groups')
    op.drop_table('telegram_groups')
    op.drop_table('keyword_usage')
    # ### end Alembic commands ###
