"""refactor schema with entities and search_runs

Revision ID: 002
Revises: 001
Create Date: 2024-02-07 15:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop old tables if they exist (handling SQLite/Postgres differences conceptually, 
    # but usually we just drop and recreate for such a breaking change in dev)
    # However, since we are "refactoring", we should drop telegram_groups.
    # KeywordUsage is kept but schema might be same.
    
    try:
        op.drop_table('telegram_groups')
    except Exception:
        pass # Might not exist or error

    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('kind', sa.Enum('USER', 'GROUP', 'CHANNEL', 'BOT', 'UNKNOWN', name='entitykind'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_kind'), 'entities', ['kind'], unique=False)
    op.create_index(op.f('ix_entities_tg_id'), 'entities', ['tg_id'], unique=True)
    op.create_index(op.f('ix_entities_title'), 'entities', ['title'], unique=False)
    op.create_index(op.f('ix_entities_username'), 'entities', ['username'], unique=False)
    
    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_runs_keyword'), 'search_runs', ['keyword'], unique=False)
    
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('NOT_JOINED', 'JOINED', 'LEFT', 'REMOVED', name='membershipstate'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_index(op.f('ix_memberships_state'), 'memberships', ['state'], unique=False)
    
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_memberships_state'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_search_runs_keyword'), table_name='search_runs')
    op.drop_table('search_runs')
    op.drop_index(op.f('ix_entities_username'), table_name='entities')
    op.drop_index(op.f('ix_entities_title'), table_name='entities')
    op.drop_index(op.f('ix_entities_tg_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_kind'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
